name: auto reply to pull requests and issues
on:
  pull_request:
    types: [opened]
    branches:
      -master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
              body: ' Thanks for contributing.We will look into it shortly.'
